// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6gRKR588gRtbnVvdDQFi5X5Hf2sfLIMQ',
    appId: '1:694692616292:web:8cff6b001ec46e4d772771',
    messagingSenderId: '694692616292',
    projectId: 'kglcity',
    authDomain: 'kglcity.firebaseapp.com',
    storageBucket: 'kglcity.firebasestorage.app',
    measurementId: 'G-F9MSJWVKZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBbh2fIqNHt9xMb3TDYKjtqUfNaZpsJBY',
    appId: '1:694692616292:android:0620b813728de528772771',
    messagingSenderId: '694692616292',
    projectId: 'kglcity',
    storageBucket: 'kglcity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZkpuKJTQrqIdZwOx-I9xyWgn5u3y3Erc',
    appId: '1:694692616292:ios:ef23822d50f02586772771',
    messagingSenderId: '694692616292',
    projectId: 'kglcity',
    storageBucket: 'kglcity.firebasestorage.app',
    iosBundleId: 'com.example.kigalicity',
  );
}
